version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8002"
    container_name: dentistAPI
    volumes:
      - .:/dentistAPI
    ports:
      - "8082:8002"